import './components/coin.js'
import './components/gsap.js'
import './components/different.js'
import './components/preloader.js'
import './components/master-card.js'
import './components/why.js'
import './components/header-scroll.js'
